Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
    
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.


x <- NULL
x[1] = 1; x[2] = 2
for (i in 3:100){
    if (x[i-1] > 4000000) stop()
    else x[i] = x[i-1] + x[i-2]
}
y <- NULL
for (i in 1:length(x)){
    if (x[i]%%2 == 0) y <- append(y, x[i])
}
sum(y)
